print('Введите текст: ')
str = input()
numStr = len(str)
print("\nДлина строки - ",numStr)
print(str.lower())
num = str.count('a') + str.count('e') + str.count('i') + str.count('o') + str.count('u')
print('Количество гласных - ',num)
print(str.replace('ugly','beauty'))
print(str[:3] == 'The' or str[(numStr-3):]=='end')